### ISSUE TITLE
Installing chrony on the MiR

### ISSUE THREAD

**Issue by TobiasRecker** [DFKI-NI/mir_robot#131]
Thanks for the idea to install chrony via the chroot environment with a bootstick. We were able to reproduce the process successfully, but had some difficulties. Maybe you could include some additional details.

What was missing in our opinion:

- before you can chroot into the MiR-PC you need to mount the SSD:
```
sudo mkdir -p /media/mir
sudo mount /media/mir/ /dev/sda3
sudo mount --bind /dev/ /media/mir/@/dev
sudo mount --bind /run/ /media/mir/@/run
``` 

- After you install chrony you need to configure it to accept connections from 192.168.12.0/24. We were not able to get the laser scanners to run otherwise.

Also we found it easier to just add a second root user and use this user to do everything over SSH:

```
adduser USERNAME
usermod -aG sudo USERNAME
```
Also for us it was simpler to just install chrony using apt. Maybe this is dangerous?
```
sudo apt update
sudo apt -f install
sudo apt install chrony
```

**Comment by mintar** [comment]
Yes, I've seen PR #130 which is also from your group. Thanks for that, I think it's worth adding this to the README.

> before you can chroot into the MiR-PC you need to mount the SSD

Yep, I was too lazy to spell it all out since there are already lots of tutorials on how to chroot into a rescue system, but I think it's good to add these instructions.

> After you install chrony you need to configure it to accept connections from 192.168.12.0/24. We were not able to get the laser scanners to run otherwise.

Thanks for fixing this! I didn't have this problem on the MiR100, but the MiR600 has different laser scanners.

> Also we found it easier to just add a second root user and use this user to do everything over SSH

Yep, I've done the same, just didn't include this in the README. Thanks.

> Also for us it was simpler to just install chrony using apt. Maybe this is dangerous?

No, this is fine, but it requires that the MiR PC has an internet connection.

Let's continue this discussion over at #130! :)
