### ISSUE TITLE
How to use ros to send a goal, which is defined in mir's map?

### ISSUE THREAD

**Issue by flymaxty** [DFKI-NI/mir_robot#21]
Hi all,
I'm trying to use rviz to send a goal to real mir robot, but it does not move. Looks like mir can not use ros to set a goal directly. Is there any way to send a goal to real mir robot in ros? Like mir mission etc..

Thank you!

**Comment by mintar** [comment]
It's possible to set a goal directly from RViz.

* Follow the steps described under "Running the driver on the real robot" in the README. Especially, you have to make sure that you launch the "Planner" (i.e., `move_base` and `amcl` on the robot). If it isn't started, when you start the mir_driver, you'll get a warning that the topic `move_base_simple/goal` is not yet subscribed to by the MiR.
* Start RViz, for example like this: `rviz -d $(rospack find mir_navigation)/rviz/navigation.rviz`
* In RViz, go to "Panels -> Tool Properties" and make sure that "2D Nav Goal -> Topic" is set to `move_base_simple/goal`.
* Run `rostopic info move_base_simple/goal` and make sure that the MiR driver is subscribed to that topic, and RViz is publishing to it.
* In RViz, make sure that "Global Options -> Fixed Frame" is set to "map".
* In RViz, click "2D Pose Estimate", then click on the map.

**Comment by rsr152** [comment]
Hi all,

I am new to the ROS framework (~2 weeks). I have been able to install ROS Kinetic in Ubuntu 16.4, run the MiR simulation in Gazebo (thanks @mintar!) and am now looking to send velocity and pose commands to the physical robot:

1. I have been able to publish to the /cmd_vel topic from the command line and move the robot forward/back and turn it clockwise/counter-clockwise using commands such as:
_rostopic pub /cmd_vel geometry_msgs/Twist -r 1 -- '[0.05, 0.0, 0.0]' '[0.0, 0.0, 0.0]'_

2. How can I get the robot to get to a particular pose (x, y, theta) from the command line?

3. In order to execute @mintar's suggestion above re: rviz, I assume I will have to map out the environment (room) first.  Is that right and if so, what is the best way to do that?

4. Finally, the robot's **position** in real life is consistent with the position returned by /robot_pose but its **orientation** is not.  Any thoughts on how to calibrate it accurately?

I would appreciate any help.  Thank you in advance!

**Comment by rsr152** [comment]
Hi all,

I am seeing the same behavior -- the (real) robot does not move after clicking on a destination in RViz.  All the settings, publications and subscriptions are in line with what @mintar has outlined above (screenshots attached).  The map displayed in RViz as well as the position of the robot in the map are accurate.

The only step I did differently was:
In RViz, I clicked "2D Nav Goal", then click on the map, as I have been doing in Gazebo.
I have not yet tried clicking on "2D Pose Estimate" and then clicking on the map because I wanted to be cautious and not have the 65kg robot run crazy in the lab :)  

Appreciate any help. As always, thank you!

Rahul

![Screenshot_2019-05-16_09-21-30](https://user-images.githubusercontent.com/47621008/57873226-731aae80-77c2-11e9-9d66-9443a967a6f5.png)
![Screenshot from 2019-05-16 09-20-17](https://user-images.githubusercontent.com/47621008/57873227-731aae80-77c2-11e9-95cf-ce2f018c0154.png)
![Screenshot from 2019-05-16 09-18-28](https://user-images.githubusercontent.com/47621008/57873228-73b34500-77c2-11e9-8208-4decc4e45bbf.png)
![Screenshot_2019-05-16_09-17-39](https://user-images.githubusercontent.com/47621008/57873229-73b34500-77c2-11e9-822e-e6cd9f1b9a22.png)

**Comment by mintar** [comment]
1. Which MiR software version do you use?
2. Are the clocks synchronized? You can check by running `rosrun tf tf_monitor`, as described in the README.

**Comment by mpatil2716** [comment]
Hi all,

I am also seeing the same behavior too -- i am using simulation robot and it does not move after clicking on a destination in RViz. I followed all the instruction given in README and all the settings, publications and subscriptions are in line with what @mintar has outlined above (screenshots attached). The map displayed in RViz as well as the position of the robot in the map are accurate.

![Gazebo](https://user-images.githubusercontent.com/49789845/58185603-63e3a700-7c81-11e9-8ddc-a2500b0565b8.png)
![Rostopic movebasesimplegoal](https://user-images.githubusercontent.com/49789845/58185605-647c3d80-7c81-11e9-8c70-05f50af9b9d9.png)
![RVIZ](https://user-images.githubusercontent.com/49789845/58185607-647c3d80-7c81-11e9-8399-6077f0ccca75.png)

Also is anyone has MiR500 or 1000 URDF package?
Appreciate any help. As always, thank you!

**Comment by rsr152** [comment]
> 1. Which MiR software version do you use?
> 2. Are the clocks synchronized? You can check by running `rosrun tf tf_monitor`, as described in the README.

1. I use MiR software 2.6.2
2. I checked the clocks synchronization and they seem to be OK with a max delay of 0.08s (screenshot attached)

![Screenshot_2019-05-30_15-32-36](https://user-images.githubusercontent.com/47621008/58669558-8153e900-82f1-11e9-9b03-18bf44c6f587.png)

**Comment by mintar** [comment]
Could you give it a try with MiR software 2.3.1 or earlier? There is currently an incompatibility with MiR software versions greater than 2.3.1.
