### ISSUE TITLE
Mir is not moving in a straight line. (mir+ur5)

### ISSUE THREAD

**Issue by Emily194** [DFKI-NI/mir_robot#54]
Hi. I am currently struggling with this issue and I have no idea why mir is not moving in a straight line. Do you know what could be the possible cause of error? Thank you!
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/65810948/82728862-ba1c7780-9d25-11ea-8df5-1dc96bda3bb3.gif)

**Comment by mintar** [comment]
Are you sure that the path is curving? Or is the start simply offset by a bit? It's a bit hard to tell by the video.

In my experiments, there is a slight offset at the start. This is caused by small perturbations in the simulation while the robot is at rest. However, the path is not significantly curved. Are any warnings printed to the terminal when you start your Gazebo simulation?

![mir_robot_straight_line](https://user-images.githubusercontent.com/320188/82879964-05a96e00-9f3e-11ea-94df-39bdb302f78a.gif)

![mobipick_straight_line](https://user-images.githubusercontent.com/320188/82880008-1528b700-9f3e-11ea-8e54-0f372eaab62c.gif)

**Comment by mintar** [comment]
Also, I've plotted the data via plotjuggler, and the path also looks to be straight:

![plotjuggler](https://user-images.githubusercontent.com/320188/82880242-6df84f80-9f3e-11ea-85cf-2c86cd080a80.png)
