### ISSUE TITLE
Simulated laser scanner does not respect namespace/prefix

### ISSUE THREAD

**Issue by matthias-mayr** [DFKI-NI/mir_robot#65]
We are using our MIR in the namespace `mir_` and initially had some issues with the navigation in simulation.

More precisely, the laser scan results on `/scan` are still in the frame `front_laser_link` rather than `mir_front_laser_link` and later on in the navigation stack this causes `amcl` to not publish the transformation between `mir_odom_comb` and `map`.

These messages are published by Gazebo using the `libgazebo_ros_laser` plugin. To work with a prefixed MIR, we had to change [the frame configuration of the plugin](https://github.com/dfki-ric/mir_robot/blob/19627a4d57dfc769cd45fb17314bb063ebd9418d/mir_description/urdf/include/sick_s300.urdf.xacro#L65) to this:
```xml
<!-- no prefix, plugin always uses a tf_prefix (if none is set it uses robotNamespace) -->
<frameName>${prefix}${link}</frameName>
```
to make it use the prefix for the frame in the published messages.

Is this, how it's supposed to be or is there another, better way to resolve this?

**Comment by mintar** [comment]
This was surprisingly tricky so solve. It took me 2 hours to figure out what the heck my colleague meant by the comment above, and more importantly, how to solve it:

```xml
<!-- no prefix, plugin always uses a tf_prefix (if none is set it uses robotNamespace) -->
```

But finally I figured it out. So the problem is that the gazebo_ros_laser plugin does the following:
- If the ROS parameter 'tf_prefix' is set, it prepends the tf_prefix in front of the frameName.
- Otherwise, it prepends the robotNamespace. (see [here](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/55cee6d0c45fd6e04353fe6020dc846252c58158/gazebo_plugins/src/gazebo_ros_laser.cpp#L129-L135))

The robotNamespace gets automatically set if you start the spawn_model node inside a namespace. In this case, if we just add `${prefix}` in front of the `frameName`, as you did, we would end up with two namespaces. Since use namespaces in our robot, that would be bad. :)

I have just pushed a couple of commits that allow you to properly set the tf prefix. You can try it like this:

```
roslaunch mir_gazebo mir_maze_world.launch tf_prefix:=mir
```

If you want to enable that behavior in your own launch file, just use the xacro arg with the catchy name of `prepend_prefix_to_laser_frame`, like this:

https://github.com/dfki-ric/mir_robot/blob/ba02a68e7bc0fcdd6942e385c61ca2b33e9d00e4/mir_description/launch/upload_mir_urdf.launch#L6

And as a demonstration of what I mean with the "pushing into namespaces" problem, I've pushed this commit to my personal fork (just for demonstration purposes, I'm not going to merge it):

https://github.com/mintar/mir_robot/commit/c91a543f9569d9b381043cc352cee30096fd754b

This is the line where I make sure not to prepend the prefix twice:

https://github.com/mintar/mir_robot/commit/c91a543f9569d9b381043cc352cee30096fd754b#diff-025925fc4708d226851d15a6422fb336R43

... because we're operating inside a namespace:

https://github.com/mintar/mir_robot/commit/c91a543f9569d9b381043cc352cee30096fd754b#diff-025925fc4708d226851d15a6422fb336R30

Feel free to reopen this issue if it's not solved by those commits.
